rename update_b2g to update_app, strip B2G_ variable prefix

diff --git a/update b/update
--- a/update
+++ b/update
@@ -56,45 +56,45 @@ function checkretval(){
     fi
 }
 
-function update_b2g () {
+function update_app () {
 
-B2G_APP_NAME="$1"
-[[ -n "$B2G_APP_NAME" ]] || abort "APP_NAME not provided to function update_b2g"
-B2G_SOURCE_PATH="$2"
-[[ -n "$B2G_SOURCE_PATH" ]] || abort "SOURCE_PATH not provided to function update_b2g"
-B2G_APP_ID="$3"
-[[ -n "$B2G_APP_ID" ]] || abort "APP_GUID not provided to function update_b2g"
+APP_NAME="$1"
+[[ -n "$APP_NAME" ]] || abort "APP_NAME not provided to function update_b2g"
+SOURCE_PATH="$2"
+[[ -n "$SOURCE_PATH" ]] || abort "SOURCE_PATH not provided to function update_b2g"
+APP_ID="$3"
+[[ -n "$APP_ID" ]] || abort "APP_GUID not provided to function update_b2g"
 
-B2G_SOURCE_URL="${FILE_URL_PREFIX}/${B2G_SOURCE_PATH}/${FILE_URL_FILENAME}"
+SOURCE_URL="${FILE_URL_PREFIX}/${SOURCE_PATH}/${FILE_URL_FILENAME}"
 
-B2G_REVISION_FILE="${CODE_DIR}/${B2G_APP_NAME}_revision.txt"
+REVISION_FILE="${CODE_DIR}/${APP_NAME}_revision.txt"
 
-B2G_LATEST_REVISION=$( get_latest_revision "${B2G_SOURCE_URL/raw-file/file}" )
-[[ -n "$B2G_LATEST_REVISION" ]] || abort "unable to fetch B2G_LATEST_REVISION from '${B2G_SOURCE_URL/raw-file/file}'"
+LATEST_REVISION=$( get_latest_revision "${SOURCE_URL/raw-file/file}" )
+[[ -n "$LATEST_REVISION" ]] || abort "unable to fetch LATEST_REVISION from '${SOURCE_URL/raw-file/file}'"
 
-B2G_OUTPUT_FILE="${VERSION_DIR}/${B2G_APP_ID}"
+OUTPUT_FILE="${VERSION_DIR}/${APP_ID}"
 
-B2G_DEPLOYED_REVISION="$(cat $B2G_REVISION_FILE)"
+DEPLOYED_REVISION="$(cat $REVISION_FILE)"
 
-if [[ "$B2G_DEPLOYED_REVISION" == "$B2G_LATEST_REVISION" ]]
+if [[ "$DEPLOYED_REVISION" == "$LATEST_REVISION" ]]
 then
     return 0
 fi
 
 # get file from Mercurial
-curl -s $B2G_SOURCE_URL -o $B2G_OUTPUT_FILE
+curl -s $SOURCE_URL -o $OUTPUT_FILE
 checkretval
 
 # remove JS comments from file
-sed -i 's/\/\/.*$//g' $B2G_OUTPUT_FILE
+sed -i 's/\/\/.*$//g' $OUTPUT_FILE
 checkretval
 
 # verify we have valid json before pushing
-cat $B2G_OUTPUT_FILE | json_verify > /dev/null
+cat $OUTPUT_FILE | json_verify > /dev/null
 checkretval
 
 # update the current revision on disk
-echo "$B2G_LATEST_REVISION" > $B2G_REVISION_FILE
+echo "$LATEST_REVISION" > $REVISION_FILE
 
 # inform the script that we need to do a deploy
 NEED_TO_DEPLOY='yes'
@@ -105,7 +105,7 @@ NEED_TO_DEPLOY='yes'
 ### Main script code.
 
 # update the b2g files on disk
-update_b2g "b2g" "b2g/app" "{3c2e2abc-06d4-11e1-ac3b-374f68613e61}"
+update_app "b2g" "b2g/app" "{3c2e2abc-06d4-11e1-ac3b-374f68613e61}"
 
 # deploy, if necessary
 if [[ "$NEED_TO_DEPLOY" == 'yes' ]]
