move VERSION_DIR mkdir from b2g to globals

diff --git a/update b/update
--- a/update
+++ b/update
@@ -15,6 +15,11 @@ VERSION=$(cat "${SRC_DIR}/version.txt")
 [[ -n "$VERSION" ]] || abort "unable to load VERSION from '${SRC_DIR}/version.txt'"
 VERSION_DIR=$CODE_DIR/$VERSION
 
+if [[ ! -d $VERSION_DIR ]]
+then
+    mkdir $VERSION_DIR || abort "unable to mkdir VERSION_DIR '${VERSION_DIR}'"
+fi
+
 function get_latest_revision () {
     [[ -n "$1" ]] || abort "url not provided to get_latest_revision"
     curl -s "$1" | grep -A1 '<td>changeset' | awk -F '[">]' '{print $9}' | awk -F '[</a]' '{print $1}' | grep -v '^$'
@@ -39,12 +44,6 @@ B2G_APP_ID="{3c2e2abc-06d4-11e1-ac3b-374f68613e61}"
 [[ -n "$B2G_APP_ID" ]] || abort "B2G_APP_ID is not set"
 
 B2G_OUTPUT_FILE="${VERSION_DIR}/${B2G_APP_ID}"
-
-if [[ ! -d $VERSION_DIR ]]
-then
-    mkdir $VERSION_DIR
-    checkretval
-fi
 
 B2G_DEPLOYED_REVISION="$(cat $B2G_REVISION_FILE)"
 
